language: c++
branches:
  only:
  - PDB-refactor

os:
  - linux

before_install:
  - sudo apt update
  - sudo apt install build-essential libglu1-mesa-dev freeglut3-dev

script:
  - cd build/gmake
  - make